FROM confluentinc/cp-kafka-connect:7.6.0

# Install Confluent JDBC Connector dari Confluent Hub
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.4

# Download MySQL Connector/J (JDBC driver) ke direktori lib connector
RUN curl -fsSL \
    "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar" \
    -o /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mysql-connector-j-8.0.33.jar
