spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=kafka-listener-group
spring.kafka.consumer.auto-offset-reset=earliest

kafka.topic.name=test-topic
kafka.schema-registry.url=http://localhost:8081
