# JAAS config untuk Kafka Broker
# KafkaServer: digunakan broker untuk mengautentikasi client yang connect via SASL_PLAINTEXT
KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/keytabs/kafka.keytab"
    principal="kafka/kafka@CONFLUENT.LOCAL";
};
