[libdefaults]
    default_realm = CONFLUENT.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    noaddresses = true

[realms]
    CONFLUENT.LOCAL = {
        kdc = kdc:88
        admin_server = kdc:749
    }

[domain_realm]
    .confluent.local = CONFLUENT.LOCAL
    confluent.local = CONFLUENT.LOCAL
    kdc = CONFLUENT.LOCAL
    kafka = CONFLUENT.LOCAL
