CREATE TABLE IF NOT EXISTS orders (
  id          INT          NOT NULL AUTO_INCREMENT,
  product     VARCHAR(255) NOT NULL,
  qty         INT          NOT NULL DEFAULT 0,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
